// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/11/2026, 3:14:35 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/RiteshKumar/Documents/github_Ritesh/Avatar/AvatarStudio/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/RiteshKumar/Documents/github_Ritesh/Avatar/AvatarStudio/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/RiteshKumar/Documents/github_Ritesh/Avatar/AvatarStudio/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/RiteshKumar/Documents/github_Ritesh/Avatar/AvatarStudio/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/RiteshKumar/Documents/github_Ritesh/Avatar/AvatarStudio/app/plugins/**/*.{js,ts,mjs}","C:/Users/RiteshKumar/Documents/github_Ritesh/Avatar/AvatarStudio/app/composables/**/*.{js,ts,mjs}","C:/Users/RiteshKumar/Documents/github_Ritesh/Avatar/AvatarStudio/app/utils/**/*.{js,ts,mjs}","C:/Users/RiteshKumar/Documents/github_Ritesh/Avatar/AvatarStudio/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/RiteshKumar/Documents/github_Ritesh/Avatar/AvatarStudio/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/RiteshKumar/Documents/github_Ritesh/Avatar/AvatarStudio/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/RiteshKumar/Documents/github_Ritesh/Avatar/AvatarStudio/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;